import { useEffect, useState } from "react";
import { db } from "@/utils/firebase";
import Head from "next/head";
import Message from "@/components/message";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Link from "next/link";

export default function Home() {
  //Creating the state with all posts
  const [allPosts, setAllPosts] = useState([]);

  const getPost = async () => {
    //Collecting the posts
    const collectionRef = collection(db, "posts");
    //Query by date
    const queryByDate = query(collectionRef, orderBy("timestamp", "desc"));
    //Update data on realtime(snapshot)
    const unsubscribe = onSnapshot(queryByDate, (snapshot) => {
      //New array of data of each document (spreading it as object)
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsubscribe;
  };

  //Running getPost
  useEffect(() => {
    getPost();
  }, []);

  return (
    <>
      <Head>
        <title>Thoughty App || JASS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="my-12 text-lg font-medium">
        <h2>See what other people are saying</h2>
        {/* <Message /> */}
        {allPosts.map((post) => (
          <Message {...post} key={post.id}>
            {/* When the comment btn is clicked it will take you to the comments(post.id) */}
            <Link href={{ pathname: `/${post.id}`, query: { ...post } }}>
              <button className="p-2 bg-cyan-500 rounded-lg text-white">
                {post.comments?.length > 0 ? post.comments?.length : 0}{" "}
                {post.comments?.length > 0 ? "comments" : "comment"}
              </button>
            </Link>
          </Message>
        ))}
      </div>
    </>
  );
}
